In [5]:
import numpy as np

In [ ]:
# Create a 1d array of numbers from 0 to 9

In [39]:
n = np.arange(10)
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
'''
Extract all odd numbers from arr
Replace all odd numbers in arr with -1
'''

In [41]:
n[n % 2 != 0]

array([1, 3, 5, 7, 9])

In [43]:
n[n % 2 != 0]  = -1
n

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
'''
Convert a 1d arr to a 2d arr with 2 rows
'''

In [45]:
n.reshape ((2,5))

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [ ]:
'''
- Get the common items between a and b using intersect1d
'''

In [82]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,4,5,5,9])
c = np.intersect1d(a,b)
#C1
for i in c:
    count_a = 0
    count_b = 0
    for j in a:
        if j == i:
            count_a += 1
    for j in b:
        if j == i:
            count_b +=1
    print(f"Số {i} xuất hiện {count_a} lần trong a và {count_b} lần trong b.")  
print('------------------------------------------------------------------------------')
#C2
for i in c:
    count_a = np.count_nonzero(a == i)
    count_b = np.count_nonzero(b == i)
    print(f"Số {i} xuất hiện {count_a} lần trong a và {count_b} lần trong b.")

Số 1 xuất hiện 1 lần trong a và 1 lần trong b.
Số 4 xuất hiện 1 lần trong a và 1 lần trong b.
Số 5 xuất hiện 1 lần trong a và 2 lần trong b.
Số 9 xuất hiện 1 lần trong a và 1 lần trong b.
------------------------------------------------------------------------------
Số 1 xuất hiện 1 lần trong a và 1 lần trong b.
Số 4 xuất hiện 1 lần trong a và 1 lần trong b.
Số 5 xuất hiện 1 lần trong a và 2 lần trong b.
Số 9 xuất hiện 1 lần trong a và 1 lần trong b.


In [ ]:
'''
- From arr a, remove all items present in arr b using setdiff1d
'''

In [86]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,4,5,5,9])
c = np.setdiff1d(a,b)
c

array([2, 3, 6, 7, 8])

In [ ]:
'''
- Get all items between 5 and 10 from a
'''

In [100]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[(a >= 5) & (a <= 10)]
b

array([5, 6, 7, 8, 9])

In [ ]:
'''
Swap columns 1 and 2 in the array and rows
'''

In [140]:
arr = np.arange(9).reshape(3,3)
print(arr[:,[2,1,0]])
print(arr[[1,2,0]])

[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[3 4 5]
 [6 7 8]
 [0 1 2]]


In [150]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter= ',', dtype='object')
sepallength = np.genfromtxt(url, delimiter= ',', dtype='float', usecols=[0])
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [162]:
print(np.mean(sepallength, axis=0)) #Neu 1d thi khong can axis
print(np.mean(sepallength))
# print(np.mean(sepallength, axis=1)) ERROR
print(np.median(sepallength, axis=0))

5.843333333333334
5.843333333333334
5.8


In [ ]:
'''
Compute the maximum for each row in the given arr
'''

In [170]:
a = np.random.randint(1, 10, [3,5])
a

array([[4, 9, 7, 1, 7],
       [4, 9, 2, 7, 1],
       [5, 6, 1, 2, 3]])

In [174]:
np.max(a, axis = 1)

array([9, 9, 6])

In [6]:
"Tạo bảng sale_mean ghi nhận doanh thu trung binh 4 thyi truong NA, EU, JP, Other theo từng tựa game "
import pandas as pd
import numpy as np

In [13]:
game= pd.read_csv('data_sales/data.csv')
game.head()

Rank      Name Platform  Yeah       Genre  NA_Sales  NA_Sales_2  EU_Sales  \
0     1        EA   Switch  2022         RPG      0.57        1.22      1.86   
1     2   Ubisoft       PC  2021  Simulation      0.67        3.34      0.65   
2     3      SEGA       PC  2024      Action      1.78        8.75      9.28   
3     4  Nintendo      PS5  2002    Fighting      4.43        9.75      6.70   
4     5        EA      PS5  2016   Adventure      7.01        3.98      2.55   

   JP_Sales  Other_Sales  Global_Sales  
0      8.21         6.47         18.33  
1      9.54         4.06         18.26  
2      6.77         0.48         27.06  
3      7.07         1.44         29.39  
4      2.49         6.68         22.71

In [41]:
mean_sale= game.groupby('Name', as_index=False)[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']].mean()
mean_sale

Name  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
0    Activision    4.6050  6.975000  7.035000     6.215000     30.600000
1  Bandai Namco    7.2700  4.963333  4.833333     9.296667     31.683333
2        Capcom    7.0000  4.020000  6.950000     3.860000     30.800000
3            EA    4.8075  5.237500  2.935000     5.472500     23.892500
4     Microsoft    3.8550  5.252500  3.930000     3.067500     22.435000
5      Nintendo    4.4300  6.700000  7.070000     1.440000     29.390000
6          SEGA    4.5600  6.435000  5.785000     3.370000     28.785000
7          Sony    4.8150  3.995000  3.835000     3.830000     21.170000
8       Ubisoft    0.6700  0.650000  9.540000     4.060000     18.260000

In [ ]:
'Tao bang publish_yeah ghi nhan nam phat hanh cua tung tua gam'

In [49]:
publish_year= game.groupby('Name')['Yeah'].min().reset_index()
publish_year

Name  Yeah
0    Activision  2001
1  Bandai Namco  2006
2        Capcom  2000
3            EA  2004
4     Microsoft  2006
5      Nintendo  2002
6          SEGA  2018
7          Sony  2005
8       Ubisoft  2021

In [ ]:
'Merge bangr mean_sale and  publish year with key is Name'

In [68]:
# merges= pd.merge(mean_sale, publish_year,
#                  on= 'Name')
merges = mean_sale.merge(publish_year, on= 'Name')
merges

Name  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  Yeah
0    Activision    4.6050  6.975000  7.035000     6.215000     30.600000  2001
1  Bandai Namco    7.2700  4.963333  4.833333     9.296667     31.683333  2006
2        Capcom    7.0000  4.020000  6.950000     3.860000     30.800000  2000
3            EA    4.8075  5.237500  2.935000     5.472500     23.892500  2004
4     Microsoft    3.8550  5.252500  3.930000     3.067500     22.435000  2006
5      Nintendo    4.4300  6.700000  7.070000     1.440000     29.390000  2002
6          SEGA    4.5600  6.435000  5.785000     3.370000     28.785000  2018
7          Sony    4.8150  3.995000  3.835000     3.830000     21.170000  2005
8       Ubisoft    0.6700  0.650000  9.540000     4.060000     18.260000  2021

In [ ]:
'''Tao bang sale gom Name, NA_Sales, EU_Sales, JP_Sales, Other_Sales
   chuyen bang sale tu wide sang long table 
'''

In [75]:
sale = game[['Name', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']]
sale

Name  NA_Sales  EU_Sales  JP_Sales  Other_Sales
0             EA      0.57      1.86      8.21         6.47
1        Ubisoft      0.67      0.65      9.54         4.06
2           SEGA      1.78      9.28      6.77         0.48
3       Nintendo      4.43      6.70      7.07         1.44
4             EA      7.01      2.55      2.49         6.68
5           Sony      0.23      6.83      2.88         2.71
6           SEGA      7.34      3.59      4.80         6.26
7      Microsoft      0.14      6.46      1.86         1.53
8      Microsoft      2.81      2.14      2.30         3.86
9             EA      2.09      9.88      0.53         7.80
10     Microsoft      3.90      6.59      9.62         0.88
11    Activision      1.59      4.32      7.87         9.98
12        Capcom      7.00      4.02      6.95         3.86
13     Microsoft      8.57      5.82      1.94         6.00
14            EA      9.56      6.66      0.51         0.94
15  Bandai Namco      8.65      8.10      0.39         8.25
16    Activision      7.62      9.63      6.20         2.45
17  Bandai Namco      7.92      0.51      6.12         9.78
18  Bandai Namco      5.24      6.28      7.99         9.86
19          Sony      9.40      1.16      4.79         4.95

In [110]:
data_long = pd.melt(sale, ['Name']) 
# INPLACE = TRUE (TRUC TIEP LEN DATA_LONG)
data_long.rename(columns= {'variable': 'Area', 'value': 'Sales'}, inplace= True)
# INPLACE = FALSE (GAN CHO 1 BIEN KHAC VA DATA OF  DATA_LONG VAN GIU NGUYEN)
No_inplace = data_long.rename(columns= {'variable': 'Area', 'value': 'Sales'})
No_inplace

Name         Area  Sales
0             EA     NA_Sales   0.57
1        Ubisoft     NA_Sales   0.67
2           SEGA     NA_Sales   1.78
3       Nintendo     NA_Sales   4.43
4             EA     NA_Sales   7.01
..           ...          ...    ...
75  Bandai Namco  Other_Sales   8.25
76    Activision  Other_Sales   2.45
77  Bandai Namco  Other_Sales   9.78
78  Bandai Namco  Other_Sales   9.86
79          Sony  Other_Sales   4.95

[80 rows x 3 columns]